### ISSUE TITLE
URL expired

### ISSUE THREAD

**Issue by Pirnazar** [kerematam/akrabatcno#1]
Helllo, can you update link to "http://www.ysk.gov.tr/ysk/index.html" because he five result "Geçersiz bir istekte bulundunuz. Yapılan tüm işlemler kayıt altına alınmaktadır." (404)

**Comment by kerematam** [comment]
Sure, thanks for the issue. I even forgot that my repo exist:D

**Comment by kerematam** [comment]
Apparently it is no longer possible to query anything via TC no alone. So i am simply removing the URL.
